POST http://127.0.0.1:8000/api/dathang/
Content-Type: application/json;charset=UTF-8

{

    "TENDANGNHAP": "admin",
    "KHACHHANG_ID": 37,
    "DATHANG_TRANGTHAI": "Đang giao",
    "DATHANG_NGAYDAT": "01/05/2004",
    "DATHANG_NGAYGIAO": "01/05/2004",
    "list":[
        {
            "SANPHAM_ID": 990888324,
            "CHITIETDATHANG_SOLUONG": 1
        }
    ]
}